#include <fstream>
#include <chrono>
#include <iomanip>
#include <random>


/* get dimension of the fvec/ivec file */
int xvec_get_dim(std::ifstream& file) {
    if(!file.is_open())
        throw std::runtime_error("Error running xvec_get_dim : file not open");

    // read 4 bytes to get dim
    int dim;
    file.read(reinterpret_cast<char*>(&dim), sizeof(std::uint32_t));

    // reset file position
    file.seekg(0, std::ios::beg);

    return dim;
}

/* import fvec/ivec file into array including file opening and closing */
template<typename datatype>
void xvecfile_to_arr(std::string dataname, std::string filetype, datatype **outdata, int arrsize, int dim) {
    std::string path = "../../data/" + dataname + "/" + dataname + filetype;
    std::ifstream datafile(path, std::ios::binary);

    if(!datafile.is_open())
        throw std::runtime_error("Failed to open gt file.\n");

    *outdata = new datatype[arrsize * dim];
    int d;
    for (int i = 0; i < arrsize; i++)
    {
        // read 4 bytes to get dim
        datafile.read(reinterpret_cast<char*>(&d), sizeof(std::uint32_t));
        if(dim != d)
            throw std::runtime_error("Error running xvec_to_arr : dims don't match");
            
        // read (dim * datatype size) bytes to get data
        datafile.read(reinterpret_cast<char*>(&(*outdata)[dim * i]), dim * sizeof(datatype));
    }

    datafile.close();
}

/* import fvec/ivec file into array */
/* remember to delete array after use */
template<typename datatype>
void xvec_to_arr(std::ifstream& file, datatype **outdata, int arrsize, int dim) {
    if(!file.is_open())
        throw std::runtime_error("Error running xvec_to_arr : file not open");

    *outdata = new datatype[arrsize * dim];
    int d;
    for (int i = 0; i < arrsize; i++)
    {
        // read 4 bytes to get dim
        file.read(reinterpret_cast<char*>(&d), sizeof(std::uint32_t));
        if(dim != d)
            throw std::runtime_error("Error running xvec_to_arr : dims don't match");
            
        // read (dim * datatype size) bytes to get data
        file.read(reinterpret_cast<char*>(&(*outdata)[dim * i]), dim * sizeof(datatype));
    }
}

/* read data generated by create_data_rand.cpp into an array */
template<typename datatype>
datatype *bin_to_arr(std::ifstream& file, std::string filename, int arrsize) {

    if (!file.is_open()) 
        throw std::runtime_error(std::string("Failed to open or process file: ") + filename);
    
    // Read sizes first
    uint32_t dim;
    file.read(reinterpret_cast<char*>(&dim), sizeof(uint32_t));
    #ifdef DEBUG
    std::cout << "reading dataset of dimension " << dim << " and size " << arrsize << std::endl;
    #endif

    // Then read data with size dim * intSize * sizeof(-)
    datatype *arr = new datatype[dim * arrsize];
    file.read(reinterpret_cast<char*>(arr), dim * arrsize * sizeof(datatype));
    
    return arr;
}

/* write data to binary file */
template<typename datatype>
bool arr_to_bin(datatype *arr, uint32_t arrSize, uint32_t dim, std::ofstream& file, std::string filename) {

    if (!file.is_open())
        throw std::runtime_error(std::string("Failed to open or process file: ") + filename);
    
    // Write size first
    file.write(reinterpret_cast<const char*>(&dim), sizeof(uint32_t));
    
    // Write data
    file.write(reinterpret_cast<const char*>(arr), arrSize * dim * sizeof(datatype));
    
    return true;
}

// /* write data to binary file */
// bool int_to_bin(int *arr, int arrsize, std::ofstream& file, std::string filename) {

//     if (!file.is_open())
//         throw std::runtime_error(std::string("Failed to open or process file: ") + filename);
    
//     // Write size first
//     file.write(reinterpret_cast<const char*>(&arrsize), sizeof(int));
    
//     // Write data
//     file.write(reinterpret_cast<const char*>(arr), arrsize * sizeof(int));
    
//     return true;
// }


// bool float_to_bin(float *arr, int arrsize, std::ofstream& file, std::string filename) {

//     if (!file.is_open()) 
//         throw std::runtime_error(std::string("Failed to open or process file: ") + filename);
    
//     // Write sizes first
//     size_t floatSize = arrsize;
//     file.write(reinterpret_cast<const char*>(&floatSize), sizeof(floatSize));
    
//     // Write data
//     file.write(reinterpret_cast<const char*>(arr), 
//                floatSize * sizeof(float));
    
//     return true;
// }

/* function to generate random data as an float array */
/* float only because data is usually represented as floats */
float *create_data(int dim, int max_elements) {
    #ifdef DEBUG
    std::cout<<"in func create_data()"<<std::endl;
    #endif
    
    std::random_device rd;
    std::mt19937 rng(rd());
    std::uniform_real_distribution<> distrib_real;

    float* data = new float[dim * max_elements];

    for (int i = 0; i < dim * max_elements; i++) {
        data[i] = distrib_real(rng);
    }

    return data;
}