#include <fstream>
#include <chrono>
#include <iomanip>
#include <random>
#include <vector>
#include <algorithm>

/*
    Under construction to replace ../code/helpers.h, which is kept to maintain backward compatibility.
*/

void normalize_vectors(float* data, int num_vectors, int dim) {
    for (int i = 0; i < num_vectors; i++) {
        float norm = 0.0;
        for (int j = 0; j < dim; j++) {
            norm += data[i * dim + j] * data[i * dim + j];
        }
        norm = sqrt(norm);
        if (norm > 0) {
            for (int j = 0; j < dim; j++) {
                data[i * dim + j] /= norm;
            }
        }
    }
}

/* get dimension of the fvec/ivec file */
int xvec_get_dim(std::ifstream& file) {
    if(!file.is_open())
        throw std::runtime_error("Error running xvec_get_dim : file not open");

    // read 4 bytes to get dim
    int dim;
    file.read(reinterpret_cast<char*>(&dim), sizeof(std::uint32_t));

    // reset file position
    file.seekg(0, std::ios::beg);

    return dim;
}

/* import fvec/ivec file into array including file opening and closing */
template<typename datatype>
void xvecfile_to_arr(std::string datapath, std::string dataname, std::string filetype, datatype **outdata, int arrsize, int dim) {
    std::string path = datapath + dataname + "/" + filetype;
    std::ifstream datafile(path, std::ios::binary);

    if(!datafile.is_open())
        throw std::runtime_error("xvecfile_to_arr : Failed to open data file.\n");

    *outdata = new datatype[arrsize * dim];
    int d;
    for (int i = 0; i < arrsize; i++)
    {
        // read 4 bytes to get dim
        datafile.read(reinterpret_cast<char*>(&d), sizeof(std::uint32_t));
        if(dim != d)
            throw std::runtime_error("Error running xvec_to_arr : dims don't match");
            
        // read (dim * datatype size) bytes to get data
        datafile.read(reinterpret_cast<char*>(&(*outdata)[dim * i]), dim * sizeof(datatype));
    }

    datafile.close();
}

/* import fvec/ivec file into array */
/* remember to delete array after use */
template<typename datatype>
void xvec_to_arr(std::ifstream& file, datatype **outdata, int arrsize, int dim) {
    if(!file.is_open())
        throw std::runtime_error("Error running xvec_to_arr : file not open");

    *outdata = new datatype[arrsize * dim];
    int d;
    for (int i = 0; i < arrsize; i++)
    {
        // read 4 bytes to get dim
        file.read(reinterpret_cast<char*>(&d), sizeof(std::uint32_t));
        if(dim != d)
            throw std::runtime_error("Error running xvec_to_arr : dims don't match");
            
        // read (dim * datatype size) bytes to get data
        file.read(reinterpret_cast<char*>(&(*outdata)[dim * i]), dim * sizeof(datatype));
    }
}

/* import fvec/ivec file into array including file opening and closing */
template<typename datatype>
bool arr_to_xvecfile(datatype *arr, uint32_t arrSize, uint32_t dim, std::ofstream& file, std::string filename) {

    if (!file.is_open())
        throw std::runtime_error(std::string("Failed to open or process file: ") + filename);
    
    for (int i = 0; i < arrSize; i++)
    {
        // Write size first
        file.write(reinterpret_cast<const char*>(&dim), sizeof(uint32_t));
        
        // Write data
        file.write(reinterpret_cast<const char*>(arr), dim * sizeof(datatype));
        arr += dim;
    }
    
    return true;
}

/* read data generated by create_data_rand.cpp into an array */
template<typename datatype>
datatype *bin_to_arr(std::ifstream& file, std::string filename, int arrsize) {

    if (!file.is_open()) 
        throw std::runtime_error(std::string("Failed to open or process file: ") + filename);
    
    // Read sizes first
    uint32_t dim;
    file.read(reinterpret_cast<char*>(&dim), sizeof(uint32_t));
    #ifdef DEBUG
    std::cout << "reading dataset of dimension " << dim << " and size " << arrsize << std::endl;
    #endif

    // Then read data with size dim * intSize * sizeof(-)
    datatype *arr = new datatype[dim * arrsize];
    file.read(reinterpret_cast<char*>(arr), dim * arrsize * sizeof(datatype));
    
    return arr;
}

/* write data to binary file */
template<typename datatype>
bool arr_to_bin(datatype *arr, uint32_t arrSize, uint32_t dim, std::ofstream& file, std::string filename) {

    if (!file.is_open())
        throw std::runtime_error(std::string("Failed to open or process file: ") + filename);
    
    // Write size first
    file.write(reinterpret_cast<const char*>(&dim), sizeof(uint32_t));
    
    // Write data
    file.write(reinterpret_cast<const char*>(arr), arrSize * dim * sizeof(datatype));
    
    return true;
}

/* function to generate random data as an float array */
/* float only because data is usually represented as floats */
float *create_data(int dim, int max_elements) {
    #ifdef DEBUG
    std::cout<<"in func create_data()"<<std::endl;
    #endif
    
    std::random_device rd;
    std::mt19937 rng(rd());
    std::uniform_real_distribution<> distrib_real(-100.0, 100.0);

    float* data = new float[dim * max_elements];

    for (int i = 0; i < dim * max_elements; i++) {
        data[i] = distrib_real(rng);
    }

    return data;
}

float *find_qs(float *data, int dim, int numq) {
    int n = numq * dim;
    float *qs = new float[n];               // Generate space
    float *temp = qs;                       // Ptr for increment

    for (int i = 0; i < n; i++)             // For each query
        *temp++ = data[i];                  // Generate random data index
    
    return qs;
}

template<typename datatype>
float percentile(std::vector<datatype> v, int p, int qnum) {
    // check for valid p
    if (p < 0 || p > 100)
        throw std::invalid_argument("Usage : 0 <= p <= 100");

    // calculate tentative index
    float i = p * (qnum-1) / 100.0f;

    // floor, ceiling
    int low = static_cast<int>(std::floor(i));
    int high = static_cast<int>(std::ceil(i));

    // if floor = ceiling return either
    if (low == high)
        return v[low];
    // else return interpolation
    else {
        float w = i - low;
        return v[low] + (v[high] - v[low]) * w;
    }
}

template<typename datatype>
float average(std::vector<datatype> vec) {
    float n = static_cast<float>(vec.size());
    float sum = 0.0;

    for (auto v : vec)
        sum += v;

    return sum / n;
}